c_compiler_version:            # [unix]
  - 12                         # [linux]
  - 15                         # [osx]
  - 10                         # [os.environ.get("CF_CUDA_ENABLED", "False") == "True" and linux]
cxx_compiler_version:          # [unix]
  - 12                         # [linux]
  - 15                         # [osx]
  - 10                         # [os.environ.get("CF_CUDA_ENABLED", "False") == "True" and linux]
llvm_openmp:                   # [osx]
  - 15                         # [osx]
