{% set name = "MDAnalysis" %}
{% set version = "0.20.0" %}
{% set sha256 = "03938fc6c25bc16af7a2f5030118e6fb3d95b47a40ac70e887ba08048d87b33f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [win and py2k]
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy >=1.10.4
    - cython

  run:
    - python
    - scipy
    - {{ pin_compatible('numpy') }}
    - matplotlib
    - seaborn
    - netcdf4
    - biopython
    - networkx
    - six
    - griddataformats >=0.4.0
    - joblib
    - gsd  # [not win]
    - mmtf-python
    - scikit-learn


test:
  imports:
    - MDAnalysis
    - MDAnalysis.analysis
    - MDAnalysis.lib.c_distances_openmp
    - MDAnalysis.lib.c_distances

about:
  home: https://www.mdanalysis.org
  license: GPLv2
  license_family: GPL
  license_file: LICENSE
  summary: 'An object-oriented library to analyze molecular dynamics trajectories generated by CHARMM, Gromacs, NAMD, LAMMPS, or Amber.'
  description: |
    MDAnalysis is a Python library to analyze trajectories from molecular
    dynamics (MD) simulations. It can read and write most popular formats, and
    provides a flexible and fast framework for writing custom analysis through
    making the underlying data easily available as NumPy arrays.
  doc_url: https://www.mdanalysis.org/docs/
  dev_url: https://github.com/MDAnalysis/mdanalysis

extra:
  recipe-maintainers:
    - kain88-de
    - orbeckst
    - richardjgowers
