travis:
  secure:
    BINSTAR_TOKEN: OJ2oRjGO46goYXflbJtq3ioB9c1w0rmfyfaraRgdWaOQGLqzogLKXL5vkM1tidepU/WR3DIMo3TpumPiyusXaTWT6MvWSZZNyMHC4G5E3AwcyQ07+ltsMdkpSd0c5PwPPVjyR1cTo8C+h/CgaMm10XGtsTxfr/MNjO8at73OI/XuYEXpqGs3xLQ1nEXSrhjqAyGZE1FqmWnl1ozOEJ1U+qZ4DG0w/G0Akd+c7K1pHbE7ahjbUHXSTT9mvOSCdkbtSZ3cO1lTubZCoH8zGsrFIBHN0QPqZsmUmpFmEXVBHjmOiHWBxTxA3cKIHyTlQ+3Q2k69AxFbtu7GRULwjVdAXg1XDQlU53p7sEByrKszmKd4cUE7A0PfiWs7J6iIK7Yoo7Vs9MkmjYyf1oW7mA7mIvi2qwl/TUv66HhM/0x9MzcTomfFBT8BcuqjEFMH8EztA+CAO4kw1UoVbVDU4Kwht6VqsuHjBqXDvSLGTjF+eCNQTLspntk16AnA7Q4wzXLZ3zYjzu26z8CvdiyQMbTE46IN7tpAQiLqVClJTFtn8/ck/Dt8JsHkj5OuRGz8DDYQUnQCjdOmdNegFM1EezyTnFSxOgMu4Q30mzJ7uvRFE8Rye4NYcUhcwoQ+rr1ISnTwUqfscMocFUA7LD3L3LXKyzaCDVelSkvmfn8eZJgW0sE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
